{{- $remoteConfigMap := dict -}}
{{- if .Values.configMap -}}
{{- range .Values.configMap -}}
{{- $configMapName := .name -}}
{{- $keys := .keys -}}
{{- $configMap := (lookup "v1" "ConfigMap" "default" $configMapName) -}}
{{- range $k, $v := $configMap.data -}}
{{- if has $k $keys -}}
{{- $_ := set $remoteConfigMap $k $v -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}

{{- $mergedValues := mergeOverwrite (fromYaml (.Files.Get $baseConfigPath)) .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  stack-config: |
{{ toYaml (mergeOverwrite $mergedValues $remoteConfigMap) | indent 4 }}
